# Build script
init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - ps: .\build.ps1 -Target=AppVeyor

# Tests
test: off

# Artifacts
artifacts:
# Static website
  - path: output

# Branches to build
branches:
  # Whitelist
  only:
    - develop